language: go

go:
  - 1.9.x
  - 1.10.x
  - tip

go_import_path: gopkg.in/src-d/core-retrieval.v0

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - env: HADOOP_VERSION=2.8.3

env:
  global:
    - DBUSER=postgres DBPASS=
  matrix:
    - HADOOP_VERSION=2.7.6
    - HADOOP_VERSION=2.8.3

services:
  - docker
  - rabbitmq
  - postgresql

addons:
  postgresql: "9.6"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - touch Gopkg.toml
  - dep ensure -v -add "github.com/coreos/etcd@3.3.10" "github.com/satori/go.uuid@b2ce2384e17bbe0c6d34077efa39dbab3e09123b"
  - make dependencies
  - go get -v gopkg.in/src-d/go-kallax.v1/...

before_script:
  - psql -c 'create database testing;' -U postgres

script:
  - make test-coverage
  - make ensure-models-generated
  - make ensure-schema-generated
